apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: dev
    stage: dev
    type: db
    service: redis
    vendor: tsjr
    app: redis
  name: tsjr-redis-dev-sg-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      stage: dev
      type: db
      service: redis
      vendor: tsjr
      environment: dev
  template:
    metadata:
      labels:
        app: redis
        stage: dev
        type: db
        service: redis
        vendor: tsjr
        environment: dev
    spec:
      containers:
        - name: redis-dev-sg-1
          image: redis:5.0-alpine
          imagePullPolicy: IfNotPresent
          args:
             - "/redis/redis.conf"
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
          ports:
            - containerPort: 6379
              name: server
          volumeMounts:
          - name: redis-data
            mountPath: /data
          - name: date-config
            mountPath: /etc/localtime
          - name: redis-config
            mountPath: /redis
      volumes:
      - name: redis-data
        hostPath:
          path: /data/redis-data/dev
          type: DirectoryOrCreate
      - name: redis-config
        configMap:
          name: dev-redis-config
          items:
          - key: redis.conf
            path: redis.conf
      - name: date-config
        hostPath:
          path: /etc/localtime
      nodeSelector:
        level: C

---
apiVersion: v1
kind: Service
metadata:
  name: redis-dev
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 26379
    protocol: TCP
  selector:
    stage: dev
    type: db
    service: redis
    vendor: tsjr
