apiVersion: v1
kind: Pod
metadata:
  name: mysql-57
  labels:
    os: ubuntu
spec:
  tolerations: #设置容忍性
  - key: "backend" 
    operator: "Equal"  #如果操作符为Exists，那么value属性可省略,如果不指定operator，则默认为Equal
    value: "sql"
    effect: "NoSchedule"
    #意思是这个Pod要容忍的有污点的Node的key是test Equal 16,效果是NoSchedule，
  - key: "nopersistvol"
    operator: "Exists" 
    effect: "PreferNoSchedule"
    tolerationSeconds: 180
 containers:
   - name: mysql-57
     image: mysql:5.7
  
# RUN
# kubectl taint node K8S-SG-A-1 backend=mysql-57:NoSchedule
# OR
# kubectl patch node K8S-SG-A-1 -p '{＂spec＂:{＂unschedulable＂:true}}'