apiVersion: v1
kind: Pod
metadata:
  name: alpine-env
spec:
  containers:
  - name: alpine
    image: alpine-ssh-server:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - mountPath: /data/conf/telegraf.conf
      name: telegraf-conf-v1
  volumes:
  - name: telegraf-conf-v1
    configMap:
      name: telegraf-conf-v1
