apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: jenkins-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: jenkins
                environment: dev
        spec:
            containers:
            - name: jenkins
              image: jenkins:2.60.3
              ports:
              - name: http-port
                containerPort: 8080
              - name: jnlp-port
                containerPort: 50000
              volumeMounts:
              - name: jenkins-home
                mountPath: /var/jenkins_home
            nodeName: 172.20.1.140
            volumes:
            - name: jenkins-home
              hostPath:
                path: /data/jk_home
                type: Directory
