apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
  annotations:
    # https://docs.traefik.io/basics/#circuit-breakers
    traefik.backend.circuitbreaker: NetworkErrorRatio() > 30%
    traefik.backend.loadbalancer.method: drr
spec:
  ports:
  - port: 8080
  selector:
    service: jenkins
    type: backend
