apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongo36: |
    port=27017  
    dbpath=/var/lib/mongodb
    logpath=/var/lib/mongodb/mongodb.log  
    logappend=true  
    fork=false
  mongo36-auth: |
    port=27017
    dbpath=/var/lib/mongodb
    logpath=/var/lib/mongodb/mongodb.log
    logappend=true
    fork=false
    keyFile=/etc/conf.d/secret-key/key
  mongos: |
    MONGOS_EXEC="/usr/bin/mongos"
    MONGOS_RUN="/var/run/mongodb"
    MONGOS_USER="mongodb"
    MONGOS_IP="127.0.0.1"
    MONGOS_PORT="27017"
    MONGOS_CONFIGDB=""
    MONGOS_OPTIONS=""
