

#!/usr/bin/expect


### ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa && ssh-copy-id -i ~/.ssh/id_rsa.pub web@172.10.10.28
set timeout 10
set user_hostname [lindex $argv 0]
set password [lindex $argv 1]
spawn ssh-copy-id $user_hostname
    expect {
        "(yes/no)?"
        {
            send "yes\n"
            expect "*assword:" { send "$password\n"}
        }
        "*assword:"
        {
            send "$password\n"
        }
    }
expect eof