{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "utcook.servicename" . }}-headless
  labels:
    app: {{ template "utcook.name" . }}
    chart: {{ template "utcook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{ .Release.Name }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "utcook.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
