apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: tomcat
spec:
    replicas: 1
    selector:
        matchLabels:
            run: tomcat
    template:
        metadata:
            labels:
                run: tomcat
        spec:
            containers:
            - name: tomcat
              image: tomcat
              ports:
              - containerPort: 8080
              env:
              - name: UMASK
                value: "0022"
              volumeMounts:
              - name: tomcat-log
                mountPath: "/usr/local/tomcat/logs"
            - name: logstash
              image: logstash
              args: ["-e input { file { path => \"/mnt/localhost_access_log.*\" } } output { stdout { codec => rubydebug } elasticsearch { hosts => [\"http://elasticsearch-svc.kiosk.svc.cluster.local:9200\"] } }"]
              volumeMounts:
              - name: tomcat-log
                mountPath: "/mnt"
            volumes:
            - name: tomcat-log
              emptyDir: {}
