apiVersion: v1
kind: Pod
metadata:
  name: downward-api-pod
  labels:
    zone: cn-east
    cluster: k8s-cluster1
    rack: rack-2
  annotations:
    build: two
    builder: zach
spec:
  containers:
  - name: downward-api-pod
    image: alpine-ssh-server:latest
    restartPolicy: OnFailure
    imagePullPolicy: IfNotPresent
    command: ["/usr/sbin/sshd","-D"]
    volumeMounts:
    - name: podinfo
      mountPath: /var/REG-ENV
      readOnly: false
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
