apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-master
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /data/mysql_master
    server: 192.168.115.6
  persistentVolumeReclaimPolicy: Recycle 

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-nfs-mysql-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-slave
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /data/mysql_slave
    server: 192.168.115.6
  persistentVolumeReclaimPolicy: Recycle 
 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-nfs-mysql-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
