---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zk-exporter-0
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: zk-exporter
    spec:
      containers:
      - name: zk-exporter-0
        image: carlpett/zookeeper_exporter:v1.0.2
        args: ["-zookeeper", "zk-0.zk-headless.public-service.svc:2181"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9141
