apiVersion: v1
kind: Service
metadata:
  name: zk-exporter
  namespace: monitoring
  labels:
    k8s-app: zk-exporter
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    k8s-app: zk-exporter
  ports:
  - name: api
    port: 9141
    protocol: TCP
