apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  creationTimestamp: '2019-08-22T07:38:15Z'
  generation: 2
  labels:
    app: alpine
  name: alpine
  namespace: default
  resourceVersion: '1153477537'
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/alpine
  uid: cd43ea38-c4af-11e9-acd5-00163e13308f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - args:
            - '1000000000000000'
          command:
            - sleep
          image: >-
            registry-vpc.cn-hangzhou.aliyuncs.com/base_containers/alpine-box:latest
          imagePullPolicy: Always
          name: alpine
          ports:
            - containerPort: 22
              hostPort: 22
              name: sshd
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-08-22T07:38:45Z'
      lastUpdateTime: '2019-08-22T07:38:45Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-08-22T07:38:15Z'
      lastUpdateTime: '2019-08-22T07:40:15Z'
      message: ReplicaSet "alpine-7d8c87457c" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
