apiVersion: v1
kind: Namespace
metadata:
  name: zach

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zach
  namespace: zach
subjects:
- kind: User
  name: zach
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
