apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tsjr-sonarqube-sg-a
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: sonarqube
                environment: dev
        spec:
            containers:
            - name: sonarqube
              image: sonarqube:lts
              ports:
              - name: http-port
                containerPort: 9000
              env:
              - name: SONARQUBE_JDBC_URL
                value: jdbc:mysql://alisql-cluster-sit:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
              - name: SONARQUBE_JDBC_USERNAME
                value: root
              - name: SONARQUBE_JDBC_PASSWORD
                value: ZACHWANG
              volumeMounts:
              - name: sonarqube-data
                mountPath: /opt/sonarqube/data
              - name: sonar-config
                mountPath: /opt/sonarqube/conf/sonar.properties
                subPath: sonar.properties
            nodeName: 172.20.1.140
            volumes:
            - name: sonarqube-data
              hostPath:
                path: /data/sonarqube
                type: Directory
            - name: sonar-config
              configMap:
                name: sonar-config
---
apiVersion: v1
kind: Service
metadata:
    name: suncash-sonarqube-9090
spec:
    type: NodePort
    selector:
        app: sonarqube
        environment: dev
    ports:
    - name: http-port
      port: 9000
