# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["localhost:9093"]
  # discover by dns
  # - dns_sd_configs:
    # - names: ['_alertmanager._tcp.xiodi.cn']
    # Dns type A/AAAA
    # type: A
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'elk'

    static_configs:
    - targets: ['172.16.48.102:9108','172.10.101.10:9108']
      labels:
        svc: 'elasticsearch'
        type: 'db'

  - job_name: 'redis'

    static_configs:
    - targets: ['172.10.10.28:9121','127.0.0.1:9121','127.0.0.1:9122']
      labels:
        svc: 'redis'
        type: 'db'

  - job_name: 'host_metric'
    file_sd_configs:
      - files:
        - /root/consul/*.json
        refresh_interval: 30s
    params:
    # 过滤需要监控的信息
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - netstat
        - filefd
        - filesystem
        - xfs
        - systemd
        
# https://blog.csdn.net/qq_25934401/article/details/84325356
  - job_name: 'app_health_check'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets: ['http://zach-cmdb.tsjinrong.cn:80', 'http://jenkinsprd.tsjinrong.cn:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
