global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The 

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'node'
    static_configs:
    - targets: ['172.16.48.102:9100']
      # 添加新的标签
      labels:
        svc: 'EC2'
        location: 'CN'
        cloudprovider: 'AWS'
        
    metric_relabel_configs:
    # 删除不需要的指标/隐藏标签
    - source_labels: [__name__]
      separator: ','
      regex: '(container_tasks_state|container_memory_failures_total)'
      action: drop
    # 将container_name该label用container替换，值保持不变, 实际上是根据已有的标签，生成一个新标签
    metric_relabel_configs:
    - source_labels: [host]
      regex: "([a-zA-Z0-9]+).tsjinrong.(top|cn)"
      replacement: $1
      target_label: hostname
      action: replace   # 可省略默认replace
    # 删除某个标签
    - regex: "host"
      action: labeldrop
      
  - job_name: "user_server_icmp_detect"
    consul_sd_configs:
    - server: "127.0.0.1:8500"
    scheme: http
    metrics_path: /probe
    params:
      module: [icmp]
    relabel_configs:
    - action: keep
      source_labels: [__meta_consul_tags]        #如果__meta_consul_tags匹配正则，则保留该目标
      regex: '.*,icmp,.*'
    - source_labels: [__meta_consul_service]
      regex: '(.+)@(.+)@(.+)'
      replacement: ${2}
      target_label: type
    - source_labels: [__meta_consul_service]
      regex: '(.+)@(.+)@(.+)'
      replacement: ${1}
      target_label: user
    - source_labels: [__address__]
      regex: (.+):(.+)
      replacement: ${1}
      target_label: __param_target
    - target_label: __address__
      replacement:  10.10.199.154:9115
    - source_labels: [__param_target]
      target_label: instance
      
  - job_name: 'cadvisor-1'
    consul_sd_configs:
    - server: 10.0.0.3:8500
      services:
        - cadvisor-1 # This is the 2nd slave
    metrics_path: /metrics/cadvisor
    scheme: https

    # 请求 kubelet metrics 接口也需要认证和授权，通常会用 webhook 方式让 apiserver 代理进行 RBAC 校验，所以还是用 ServiceAccount 的 token
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    kubernetes_sd_configs:
    - role: node

    # 通常不校验 kubelet 的 server 证书，避免报 x509: certificate signed by unknown authority
    tls_config:
      insecure_skip_verify: true

    relabel_configs:
    - source_labels: [__address__]
      modulus:       4    # 将节点分片成 4 个 group
      target_label:  __tmp_hash
      action:        hashmod
    - source_labels: [__tmp_hash]
      regex:         ^1$  # 只抓第 2 个 group 中节点的数据(序号 0 为第 1 个 group)
      action:        keep