{{- if .Values.serviceMonitor.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  labels:
  labels:
    app: {{ template "ceph-exporter.name" . }}
    chart: {{ template "ceph-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.serviceMonitor.additionalServiceMonitorLabels }}
{{ toYaml .Values.serviceMonitor.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}
  name: {{ template "ceph-exporter.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
subsets:
  - addresses:
      {{- range .Values.serviceMonitor.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: {{ .Values.serviceMonitor.scheme }}-metrics
        port: {{ .Values.serviceMonitor.exporterPort }}
        protocol: TCP
{{- end }}
