apiVersion: v1
kind: Service
metadata:
  name: httpd-deploy-lb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: httpd
    type: web
  type: LoadBalancer
