[template]
; default path "/"
; prefix = "/myapp"  
; USE FOLLOWING COMMAND TO CREATE BACKEND DATASTORE
; etcdctl set /myapp/subdomain myapp
; etcdctl set /myapp/upstream/app2 "10.0.1.100:80"
; etcdctl set /myapp/upstream/app1 "10.0.1.101:80"

; src = "myapp-nginx.tmpl"
src = "myapp-nginx.tmpl"
dest = "/etc/nginx/conf.d/myapp-nginx.conf"
owner = "nginx"
mode = "0644"
keys = [
	"/web/nginx/103",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/service nginx reload"