apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: prd
    stage: prd
    type: message
    service: rabbitmq
    vendor: tsjr
    app: rabbitmq
  name: tsjr-rabbitmq-prd-sg-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      stage: prd
      type: message
      service: rabbitmq
      vendor: tsjr
      environment: prd
  template:
    metadata:
      labels:
        app: rabbitmq
        stage: prd
        type: message
        service: rabbitmq
        vendor: tsjr
        environment: prd
    spec:
      containers:
        - name: rabbitmq-prd-sg-1
          image: rabbitmq:3-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
          ports:
            - containerPort: 5672
              name: server
            - containerPort: 15672
              name: erlang
            - containerPort: 25672
              name: web
          volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
          - name: date-config
            mountPath: /etc/localtime
      volumes:
      - name: rabbitmq-data
        hostPath:
          path: /data/rabbitmq-data/prd
          type: Directory
      - name: date-config
        hostPath:
          path: /etc/localtime
      nodeSelector:
        level: C

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server-prd
spec:
  type: NodePort
  ports:
  - port: 5672
    nodePort: 22001
    protocol: TCP
  selector:
    stage: prd
    type: message
    service: rabbitmq
    vendor: tsjr

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-prd
spec:
  type: NodePort
  ports:
  - port: 15672
    nodePort: 22002
    protocol: TCP
  selector:
    stage: prd
    type: message
    service: rabbitmq
    vendor: tsjr

