# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      #- alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
#  - "rules/*.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

#  - job_name: 'DB14_service'
#    static_configs:
#    - targets: ['202.120.39.167:9989']
#      labels:
#        appname: 'DB14_service'
  - job_name: '交大服务机器'
    file_sd_configs:
    - files:
      - configs/node.json
      refresh_interval: 1m

  - job_name: '交大集群的http_check'
    scrape_interval: 15s
    #scrape_timeout: 20m
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
    - files:
      - configs/http.json
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.28.116:9115

  - job_name: '小程序域名https_check'
    scrape_interval: 15s
    #scrape_timeout: 20m
    metrics_path: /probe
    params:
      module: [https_post_health]
    file_sd_configs:
    - files:
      - configs/https.json
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.28.116:9115

  - job_name: '交大集群api_detection'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_api_detection]
    file_sd_configs:
    - files:
      - configs/api.json
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.28.116:9115
