apiVersion: batch/v1
kind: Job
metadata:
  name: consul-dev-backup-job
spec:
  template:
    spec:
      containers:
      - name: consul-dev-backup-job
        image: consul:1.4.4
        imagePullPolicy: IfNotPresent
        command: ["consul","snapshot","save","--http-addr=http://consul-dev:8500","/consul-backup/consul-dev-backup.consul"]
        volumeMounts:
        - name: consul-backup
          mountPath: /consul-backup
      restartPolicy: OnFailure
      volumes:
      - name: consul-backup
        hostPath:
          path: /tsjr-data/databackup/consul-backup
          type: Directory
      restartPolicy: OnFailure
