apiVersion: v1
kind: Service
metadata:
  name: java-jdk-8-zach
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32001
    protocol: TCP
  selector:
    type: backend
    service: java-jdk-8-zach
