apiVersion: v1
kind: PersistentVolume
metadata:
  name: webdata-zach-web-sts-0
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 172.16.49.92
    path: /data/zach-web/stor1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webdata-zach-web-sts-1
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 172.16.49.92
    path: /data/zach-web/stor2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webdata-zach-web-sts-2
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 172.16.49.92
    path: /data/zach-web/stor3
