FROM nvidia/cuda:10.2-devel-ubuntu18.04
LABEL MAINTAINER ZACH.WANG
ENV CN_REPO_URL mirrors.aliyun.com
ENV TZ=Asia/Shanghai
RUN  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo '$TZ' > /etc/timezone && \ 
    rm -rf /etc/apt/sources.list.d/* && sed -i "s/deb.debian.org/${CN_REPO_URL}/g" /etc/apt/sources.list && \
    sed -i "s/security.debian.org/${CN_REPO_URL}/g" /etc/apt/sources.list && \
    apt update -y 
	
RUN apt-get install -y locales
RUN locale-gen zh_CN.UTF-8 && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
ENV LANG zh_CN.UTF-8  
ENV LANGUAGE zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8




