apiVersion: v1
kind: Node
metadata:
  name: K8S-SG-A-1
  labels:
    kubernetes.io/hostname: K8S-SG-A-1
spec:
  unschedulable: true
  
# RUN
# kubectl replace -f unschedule_node.yaml
# OR
# kubectl patch node K8S-SG-A-1 -p '{＂spec＂:{＂unschedulable＂:true}}'