global:
  resolve_timeout: 5m
  smtp_from: dev@zach.cn
  smtp_smarthost: smtp.qiye.aliyun.com:465
  smtp_auth_username: dev@zach.cn
  smtp_auth_password: pwd666
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'MonitorSystem'
  routes:
  - match:
      severity: critical
    receiver: MonitorSystem
  - match_re:
      severity: ^(warning|critical)$
    receiver: mail

#templates:
#  - '/root/prometheus/alertmanager-0.15.3.linux-amd64/template/*.tmpl'


receivers:
# dingding webhook method
- name: 'MonitorSystem'
  webhook_configs:
  - url: "http://127.0.0.1"
  
- name: 'mail'
  email_configs:
  - to: "zach@zach.cn"
  
- name: 'host'
  email_configs:
  - send_resolved: true
    to: test@qq.com
    
# Wechat method
- name: 'wechat'
  wechat_configs:
  - corp_id: 'xxx'
    to_party: '1'
    agent_id: '1000002'
    api_secret: 'xxxx'
		
inhibit_rules: 
  - source_match: 
     severity: 'critical' 
    target_match: 
     severity: 'warning' 
    equal: ['alertname', 'dev', 'instance']
