global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'MonitorSystem'
  routes:
  - match:
      severity: critical
    receiver: MonitorSystem
  - match_re:
      severity: ^(warning|critical)$
    receiver: mail

#templates:
#  - '/root/prometheus/alertmanager-0.15.3.linux-amd64/template/*.tmpl'

receivers:
- name: 'MonitorSystem'
  webhook_configs:
  - url: "http://127.0.0.1"
- name: 'mail'
  email_configs:
  - to: "zach@zach.cn"
  
inhibit_rules: 
  - source_match: 
     severity: 'critical' 
    target_match: 
     severity: 'warning' 
    equal: ['alertname', 'dev', 'instance']
