apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tsjr-mysql-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      stage: local
      type: db
      service: mysql
      version: v5.6 
  template:
    metadata:
      labels:
        belong: backend
        stage: local
        type: db
        service: mysql
        version: v5.6
    spec:
      initContainers:
      - name: mysql-init
        image: busybox
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_INIT_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pwd
              key: mysql-root-pwd
        command:  
          - sh
          - "-c"
          - |
            set -ex
            rm -fr /var/lib/mysql/lost+found
            cat > /docker-entrypoint-initdb.d/mysql-root-init.sql <<EOF
            grant all on *.* to 'root'@'%' identified by '$MYSQL_INIT_USER_PASSWORD';
            flush privileges;
            EOF
            cat > /docker-entrypoint-initdb.d/mysql-databases-init.sql <<EOF
            create database app;
            create table app(id int);
            insert into app values(1);
            commit;
            EOF
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: mysql-cluster
        image: harbor.tsjinrong.cn/k8s-zach/mysql:5.6
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pwd
              key: mysql-root-pwd
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pwd
              key: mysql-root-user
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - "-c"
            - MYSQL_PWD="${MYSQL_ROOT_PASSWORD}"
            - mysql -h 127.0.0.1 -u root -e "SELECT 1"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - "-c"
            - MYSQL_PWD="${MYSQL_ROOT_PASSWORD}"
            - mysql -h 127.0.0.1 -u root -e "SELECT 1"
          initialDelaySeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: mysql-initdb
        emptyDir: {}
      - name: mysql-data
        hostPath:
          path: /data/web
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: 172.16.50.11
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    belong: backend
    stage: local
    type: db
    service: mysql
    version: v5.6
  name: mysql-cluster
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 33306
    protocol: TCP
    targetPort: 3306
  selector:
    belong: backend
    stage: local
    type: db
    service: mysql
    version: v5.6

