apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tsjr-alisql-cluster-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      stage: prd
      type: db
      service: alisql
      version: v5.6.32 
  template:
    metadata:
      labels:
        belong: backend
        stage: prd
        type: db
        service: alisql
        version: v5.6.32
    spec:
      containers:
      - name: alisql-cluster-prd
        image: alisql/alisql:5.6.32
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: alisql-data
        - name: alisql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: date-config
          mountPath: /etc/localtime
        - name: alisql-config
          mountPath: /etc/mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alisql-pwd
              key: alisql-root-pwd
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - "-c"
            - MYSQL_PWD="${MYSQL_ROOT_PASSWORD}"
            - mysql -h 127.0.0.1 -u ${MYSQL_USER} -e "SELECT 1"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - "-c"
            - MYSQL_PWD="${MYSQL_ROOT_PASSWORD}"
            - MYSQL -h 127.0.0.1 -u ${MYSQL_USER} -e "SELECT 1"
          initialDelaySeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
      volumes:
      - name: alisql-initdb
        emptyDir: {}
      - name: alisql-data
        hostPath:
          path: /data/databases/alisql-prd
          type: Directory
      - name: date-config
        hostPath:
          path: /etc/localtime
      - name: alisql-config
        configMap:
          name: dev-alisql-config
          items:
          - key: my.cnf
            path: my.cnf
      nodeSelector:
        kubernetes.io/hostname: 172.20.1.142
 
