apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: httpd-2
  labels:
    type: web
    service: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      type: web
      service: httpd
  # when pod ready it willl success
  minReadySeconds: 1
  # Deploy max wait 60 seconds. if not success ,it will consider to failed.
  progressDeadlineSeconds: 60
  # rollback max version num default 10
  revisionHistoryLimit: 5
  strategy:
  # recreate it will kill all pods present
  # type: Recreate 
  # RollingUpdate allow deploy new without downtime
    type: RollingUpdate
    rollingUpdate:
      # When go RollingUpdate ,it will start 1 pod
      maxSurge: 1
      # Maximum number of pods allowed for RollingUpdate
      maxUnavailable: 1
      ### Use percentage to update max pods equal replicas * (1+25%)
      # maxSurge: "25%"
      # maxUnavailable: "25%"
  template:
    metadata:
      labels:
        type: web
        service: httpd
        language: c99
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        imagePullPolicy: IfNotPresent
