apiVersion: v1
kind: Service
metadata:
  name: redis-externalip-svc
  labels:
    app: redis-externalip
spec:
  ports:
  - port: 64379
  externalIPs:
  - 172.16.49.88
  selector:
    app: redis-externalip
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-externalip-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-externalip
    spec:
      containers:
      - name: redis-out
        image: redis:latest
        ports:
        - containerPort: 6379
---
