apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
spec:
    type: LoadBalancer
    selector:
        app: wordpress
    ports:
        - port: 80
          targetPort: http-port
          protocol: TCP
