apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx-tranproxy
  name: nginx-tranproxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx-tranproxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx-tranproxy
    spec:
      containers:
      - image: lijiaocn/nginx-tranproxy:0.1
        imagePullPolicy: IfNotPresent
        name: nginx-tranproxy
        args:
        - -P
        - "80"
        - -P
        - "8080"
        - -N
        - "114.114.114.114"
        - -N
        - "8.8.8.8"
        - --Set-Forwarded-For
        - default
        - --Set-Client-Hostname
        - default
        - -H
        - tranproxy:true
        env:
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
