apiVersion: v1
kind: Service
metadata:
  name: zookeeper-standalone
  labels:
    app: zookeeper-standalone
spec:
  type: NodePort
  ports:
  - port: 2181
    name: client
    nodePort: 32181
  selector:
    app: zk-standalone
