apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-zach
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 36379
    protocol: TCP
  selector:
    app: redis-ha
    redis-role: master
