kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ssl-configmap-suncash
data:
  suncashlending.com.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIGhzCCBW+gAwIBAgIQTnOkc9pBAEQXZIIUfBTuTDANBgkqhkiG9w0BAQsFADCB
    jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
    A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
    Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
    MB4XDTE5MDQxOTAwMDAwMFoXDTIxMDQxODIzNTk1OVowYjEhMB8GA1UECxMYRG9t
    YWluIENvbnRyb2wgVmFsaWRhdGVkMR4wHAYDVQQLExVFc3NlbnRpYWxTU0wgV2ls
    ZGNhcmQxHTAbBgNVBAMMFCouc3VuY2FzaGxlbmRpbmcuY29tMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPZonDq+Wl/5kVZzTbLwNKyrmqQDteWdS+vD
    OJvNng1+N/7g/6QHL8Mg4A4M8HRG+8W2GySIqB4uG6Y4e6Uvyb09fzQOqxPgdvOg
    tjF9k1e7f8OBCyyGuKkT40rpiyA9UNg5GQ9fhNNHrYsC9xSsahGEtWCtOB9xbrgJ
    cd8owlNh8qHIxC7azZMNo3hdaUZcd082rBhFggT4pYB7UBmP4yAmNgpnCpMzeShD
    hx0pzR99wgLy1YY6X1ut1bS4Fk6fjppB633Uw2Gsg/OulvoxyesywNNWFPHfFIKI
    QWP5j9xBNfGJtZoBAcZ5jsfFL8aYtax2CzM2DQY0qtcvhNsRQQIDAQABo4IDCTCC
    AwUwHwYDVR0jBBgwFoAUjYxexFStiuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFFHJ
    Nr9RHGPOPi6fIN+y9tMEMnXAMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
    MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysG
    AQQBsjEBAgIHMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BT
    MAgGBmeBDAECATCBhAYIKwYBBQUHAQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8v
    Y3J0LnNlY3RpZ28uY29tL1NlY3RpZ29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJl
    U2VydmVyQ0EuY3J0MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNv
    bTAzBgNVHREELDAqghQqLnN1bmNhc2hsZW5kaW5nLmNvbYISc3VuY2FzaGxlbmRp
    bmcuY29tMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdwC72d+8H4pxtZOUI5eq
    kntHOFeVCqtS6BqQlmQ2jh7RhQAAAWo0K1HaAAAEAwBIMEYCIQD/nbN7Mdxm9W10
    noinoqMZazM9BRJ4WN3xR0sd2RBkKAIhAPZrAayNAOePJ8ALaasVpYxKTkOJG58S
    LDcTm6IMrnTvAHUARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAFq
    NCtSCgAABAMARjBEAiAiclc89WeDNjsQTH1m6KXB/u0N9IM0NNiNnASfdi2MWAIg
    B7PZWXsh5feuJDUEQAQGME/PfA26KC1oOFbhqg4DNIsAdQBc3EOS/uarRUSxXprU
    VuYQN/vV+kfcoXOUsl7m9scOygAAAWo0K1MQAAAEAwBGMEQCIFwj8QrUj+S0on9+
    HCHcMaO/YNe5+O8m+I5DAVt3uRcXAiBwG0ZXFmwzfRHpl44hPBAkuPyjeR/fRDTc
    if7xX/4R2zANBgkqhkiG9w0BAQsFAAOCAQEAsNGdRMYXMORHpUnpKAQbn8BNWsw/
    50bRkq3HTBXD/WLWuby/0XAr2hKgW0bGBJfrQmTDJ3cowDtCcljdRahUpoEE5kgV
    dW6LWGVfBBTdFJPVJYtyD40WK4ChCuO3QcvX/UsIAj+0QBV/rTNyoI0GtqEIDZEU
    ME4/UeJHpqj9GLJTrvCiMCak10jqyoyn4l7XDpVT0+utK33MauPIDIlhRkX+4r/z
    0jUmTZjy3sMsuq1qjAbOI3R1x4rOOLNHNOZMLNCvUwWAkDiEbmsoP8E9hncIZkey
    hhH5lufZjzgG16mfl5IwWx6MW1CP4kBqtg5Ey7ClXoLi+tXXGuNUXUk+lg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
    MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
    BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
    ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
    VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
    TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
    eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
    oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
    Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
    uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
    BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
    +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
    CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
    LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
    BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
    bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
    L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
    ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
    7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
    H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
    RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
    xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
    sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
    l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
    6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
    LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
    yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
    00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIF3jCCA8agAwIBAgIQAf1tMPyjylGoG7xkDjUDLTANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTAw
    MjAxMDAwMDAwWhcNMzgwMTE4MjM1OTU5WjCBiDELMAkGA1UEBhMCVVMxEzARBgNV
    BAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0plcnNleSBDaXR5MR4wHAYDVQQKExVU
    aGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMTJVVTRVJUcnVzdCBSU0EgQ2Vy
    dGlmaWNhdGlvbiBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQCAEmUXNg7D2wiz0KxXDXbtzSfTTK1Qg2HiqiBNCS1kCdzOiZ/MPans9s/B
    3PHTsdZ7NygRK0faOca8Ohm0X6a9fZ2jY0K2dvKpOyuR+OJv0OwWIJAJPuLodMkY
    tJHUYmTbf6MG8YgYapAiPLz+E/CHFHv25B+O1ORRxhFnRghRy4YUVD+8M/5+bJz/
    Fp0YvVGONaanZshyZ9shZrHUm3gDwFA66Mzw3LyeTP6vBZY1H1dat//O+T23LLb2
    VN3I5xI6Ta5MirdcmrS3ID3KfyI0rn47aGYBROcBTkZTmzNg95S+UzeQc0PzMsNT
    79uq/nROacdrjGCT3sTHDN/hMq7MkztReJVni+49Vv4M0GkPGw/zJSZrM233bkf6
    c0Plfg6lZrEpfDKEY1WJxA3Bk1QwGROs0303p+tdOmw1XNtB1xLaqUkL39iAigmT
    Yo61Zs8liM2EuLE/pDkP2QKe6xJMlXzzawWpXhaDzLhn4ugTncxbgtNMs+1b/97l
    c6wjOy0AvzVVdAlJ2ElYGn+SNuZRkg7zJn0cTRe8yexDJtC/QV9AqURE9JnnV4ee
    UB9XVKg+/XRjL7FQZQnmWEIuQxpMtPAlR1n6BB6T1CZGSlCBst6+eLf8ZxXhyVeE
    Hg9j1uliutZfVS7qXMYoCAQlObgOK6nyTJccBz8NUvXt7y+CDwIDAQABo0IwQDAd
    BgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rIDZsswDgYDVR0PAQH/BAQDAgEGMA8G
    A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEMBQADggIBAFzUfA3P9wF9QZllDHPF
    Up/L+M+ZBn8b2kMVn54CVVeWFPFSPCeHlCjtHzoBN6J2/FNQwISbxmtOuowhT6KO
    VWKR82kV2LyI48SqC/3vqOlLVSoGIG1VeCkZ7l8wXEskEVX/JJpuXior7gtNn3/3
    ATiUFJVDBwn7YKnuHKsSjKCaXqeYalltiz8I+8jRRa8YFWSQEg9zKC7F4iRO/Fjs
    8PRF/iKz6y+O0tlFYQXBl2+odnKPi4w2r78NBc5xjeambx9spnFixdjQg3IM8WcR
    iQycE0xyNN+81XHfqnHd4blsjDwSXWXavVcStkNr/+XeTWYRUc+ZruwXtuhxkYze
    Sf7dNXGiFSeUHM9h4ya7b6NnJSFd5t0dCy5oGzuCr+yDZ4XUmFF0sbmZgIn/f3gZ
    XHlKYC6SQK5MNyosycdiyA5d9zZbyuAlJQG03RoHnHcAP9Dc1ew91Pq7P8yF1m9/
    qS3fuQL39ZeatTXaw2ewh0qpKJ4jjv9cJ2vhsE/zB+4ALtRZh8tSQZXq9EfX7mRB
    VXyNWQKV3WKdwrnuWih0hKWbt5DHDAff9Yk2dDLWKMGwsAvgnEzDHNb842m1R0aB
    L6KCq9NjRHDEjf8tM7qtj3u1cIiuPhnPQCjY/MiQu12ZIvVS5ljFH4gxQ+6IHdfG
    jjxDah2nGN59PRbxYvnKkKj9
    -----END CERTIFICATE-----
  suncashlending.com.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAxPZonDq+Wl/5kVZzTbLwNKyrmqQDteWdS+vDOJvNng1+N/7g
    /6QHL8Mg4A4M8HRG+8W2GySIqB4uG6Y4e6Uvyb09fzQOqxPgdvOgtjF9k1e7f8OB
    CyyGuKkT40rpiyA9UNg5GQ9fhNNHrYsC9xSsahGEtWCtOB9xbrgJcd8owlNh8qHI
    xC7azZMNo3hdaUZcd082rBhFggT4pYB7UBmP4yAmNgpnCpMzeShDhx0pzR99wgLy
    1YY6X1ut1bS4Fk6fjppB633Uw2Gsg/OulvoxyesywNNWFPHfFIKIQWP5j9xBNfGJ
    tZoBAcZ5jsfFL8aYtax2CzM2DQY0qtcvhNsRQQIDAQABAoIBAGRG55+SsNMmRdNe
    5jlKvsyylHOYyWLUUi8TC0NI33h2eipcE4VTp20DtTsdLC1HpdQNJtfO09xz8RmW
    mO8qfJgDRsn6YPVsmz00cEASFlLrucQkbxCXTMe7HSr9OsXgVhdQ3lEJ6KGhR77t
    JUdSOS2PWbdWTxpht8ic3gIhkYjNMkvi1w8RkL5QFM/3OU969pPhQpM7tsoUG+Be
    nzdXcFpp7i0Q2J2gW0AkxffPvVaeBWWfJaVHaZ6tssgP1379/99mGxg7iu0a8aXW
    ZM8e9GwqQmcNx8R/KILELV40qZQ8sQqrTARyrczsSxeaUgy7q1cPk+oIKgRlgKMw
    G2EEnoECgYEA4hIYRi9KaMGyJRFXQ3XtxAOR9c+dJ9sr7/6M6pGWpU1N/9ud3Sis
    gOv5eKA/WAUFL4rxB2pcSZ9mzmRJnxzJJ5QUDT+2mUXOzWligVwShUtZMazVyGyc
    z8H80pEBfYnmZu/VXZC+U3hOIqMD++djBoyXInoF1uiiBKg+hyhvfakCgYEA3wnK
    gQw9ndOWPyGilnRFuIRAbxeCwefjYGvyO8t1H6JHYXws0DxGiQ4MsfokWfcnw1C1
    DrledZco1cMgIB551J7qPFsybGPTbAaiOFAZIlXLJP2V3HOpR9ajHBFRj4UTcXkB
    tmOBmd4of+SOokxpVw+59H4iL06/RG3SOkSDRdkCgYA2yeHeKJnk94SAHUrDy7Ha
    /m6CX1WcEi780/k85BnZZ/nOV2BT+AaOnCHyzQts/pJ6Kjct7+X75cjZnk6FZEmP
    8QBHEbjkPpnXCIJaDYFjkpZERrns//2lEEOAmKn+zcvsCJXyPiESQ6bUGCPgCfzi
    2nHKZj5CDlEtxcSZpwAWOQKBgCd+n1pMpZiOABv7w8OqoTH0UUiavC/D9TJ8yu8l
    rv7ECKnNiE3zbnYUg9D8P3Wi22qtnvIVhxGBi9yWadjmLKKm5Ul8yKgC4UxOvGkG
    Xf0Dfi51rRTVclNjQYzV0EB+yxub1t7KLgfmG/vRqCQ7LagaA860iy8fXaUrYT+q
    JCi5AoGBANQsz6UtBuLQ6FOKS/9Yw8dG694AtgxEScq4q0jGqlzxZoJYM4+xTaJ/
    zfXAuRpNsd4p7/0waAcz5gGw+t164yB0K2gJkt1dPIOIzKyTYX3+EscT3JFaTnAB
    w6fFC2o8MfT4UkJ6Tah3/vd5lBvBGI7lN1NLHlyEkMWzRWES0W+a
    -----END RSA PRIVATE KEY-----
