---
apiVersion: v1
kind: Service
metadata:
  name: zk-nodeport
  namespace: kafka
  labels:
    app: zk
spec:
  type: NodePort
  ports:
  - port: 2181
    nodePort: 32181
    protocol: TCP
    name: zk-server
  selector:
    app: zk
