version: '2'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
    - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
