{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elastichd.fullname" . }}
  labels:
    app: {{ template "elastichd.name" . }}
    chart: {{ template "elastichd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
data:
{{ toYaml .Values.config.data | indent 2 }}
{{- end -}}
