apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alpine-env-secret-2
spec:
  selector:
    matchLabels:
      type: alpine
      service: os
  template:
    metadata:
      labels:
        type: alpine
        service: os
    spec:
      nodeSelector:
        level: B
      containers:
      - name: alpine
        image: alpine-ssh-server:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep"]
        args: ["100000"]
        env:
        - name: SECRETS_DIR
          value: /etc/secrets
        volumeMounts:
        - name: jenkins
          mountPath: /etc/secrets
        #readOnly: true
      volumes:
      - name: jenkins
        secret:
          secretName: jenkins-sec
          #defaultMode: 0444
          items:
          # key must the same as secretName data
          - key: username
          # path is the route of pods volumes EG: the follow actrual path is /etc/secrets/jenkins-user
            path: jenkins-user
          - key: password
            path: jenkins-pass
