apiVersion: v1
kind: Service
metadata:
  name: elastalert
  namespace: syslog
  labels:
    k8s-app: elastalert
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "elastalert"
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    k8s-app: elastalert
