apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alpine-ssh-server
  labels:
    type: os
    service: sshd
spec:
  replicas: 2
  selector:
    matchLabels:
      type: os
      service: sshd
  # when pod ready it willl success
  minReadySeconds: 1
  # Deploy max wait 60 seconds. if not success ,it will consider to failed.
  progressDeadlineSeconds: 60
  # rollback max version num default 10
  revisionHistoryLimit: 5
  strategy:
  # recreate it will kill all pods present
  # type: Recreate 
  # RollingUpdate allow deploy new without downtime
    type: RollingUpdate
    rollingUpdate:
      # When go RollingUpdate ,it will start 1 pod
      maxSurge: 1
      # Maximum number of pods allowed for RollingUpdate
      maxUnavailable: 1
  template:
    metadata:
      labels:
        type: os
        service: sshd
        language: c
    spec:
      containers:
      - name: alpine
        image: alpine-ssh-server:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep"]
        args: ["100000"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
