apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: dev
    stage: dev
    type: register
    service: consul
    vendor: tsjr
    app: consul
  name: tsjr-consul-dev-sg-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
      stage: dev
      type: register
      service: consul
      vendor: tsjr
      environment: dev
  template:
    metadata:
      labels:
        app: consul
        stage: dev
        type: register
        service: consul
        vendor: tsjr
        environment: dev
    spec:
      containers:
        - name: consul
          image: consul:1.4.4
          imagePullPolicy: IfNotPresent
          args:
             - "agent"
             - "-server"
             - "-bootstrap"
             - "-datacenter=zach"
             - "-ui"
             - "-data-dir=/data"
             - "-bind=0.0.0.0"
             - "-client=0.0.0.0"
             - "-advertise=$(PODIP)"
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
          volumeMounts:
          - name: consul-data
            mountPath: /data
          - name: date-config
            mountPath: /etc/localtime
      volumes:
      - name: consul-data
        hostPath:
          path: /tsjr-data/consul-data
          type: Directory
      - name: date-config
        hostPath:
          path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: consul-dev
spec:
  type: NodePort
  ports:
  - port: 8500
    nodePort: 28080
    protocol: TCP
  selector:
    stage: dev
    type: register
    service: consul
    vendor: tsjr
