---
apiVersion: v1
kind: Pod
metadata:
  name: openebs-demo-pod
spec:
  containers:
    - name: web-server
      image: docker.io/library/nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: local-hostpath-pvc
        readOnly: false
