version: '3'
services:
  redis-master:
    image: redis:3.2.12-alpine
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
      - ./master/data:/data
    ports: 
      - 6455:6455
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-slave:
    image: redis:3.2.12-alpine
    depends_on:
      - redis-master
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
      - ./slave/data:/data
    ports: 
      - 6458:6458
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-slave2:
    image: redis:3.2.12-alpine
    depends_on:
      - redis-master
    volumes:
      - ./slave2/redis.conf:/usr/local/etc/redis/redis.conf
      - ./slave2/data:/data
    ports: 
      - 6458:6458
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]