apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - image: busybox:laSPS
    name: SPS-container
    command:
    - sleep
    - "6000"
    volumeMounts:
    - mountPath: /mounted_volume
      name: SPS-volume
  restartPolicy: Never
  hostPID: false
  hostIPC: false
  securityContext:
    seLinuxOptions:
      level: "s0:c2,c3"
  volumes:
  - name: SPS-volume
    emptyDir: {}