apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - image: busybox:laSPS
    name: SPS-container
    command:
    - sleep
    - "6000"
  dnsPolicy: ClusterFirst
    resources: {}
    securityContext:
    runAsNonRoot: true
      capabilities:
      add:
        - IPC_LOCK
        - SYS_RESOURCE
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000
      # privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File