apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  # Disallow sharing of the host process ID namespace
  hostPID: false
  # Disallow sharing of the host IPC namespace (i.e. memory)
  hostIPC: false
  # Disallow sharing of the host network stack
  hostNetwork: false
  # Require the container to run without root privileges.
  runAsUser:
    rule: 'MustRunAsNonRoot'
  # Forbid adding the root group.
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  defautlAllowPrivilegeEscalation: false