apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: neo4j-local-dev-backup-job
  namespace: neo4j
spec:
  schedule: "30 2 * * *"
  startingDeadlineSeconds: 30
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: level
                    operator: In
                    values:
                    - A
          containers:
          - name: neo4j-local-dev-backup-job
            image: neo4j:3.5.5-enterprise
            imagePullPolicy: IfNotPresent
            command: 
            - sh
            - "-c"
            - |
              set -e
              rm -rf /data/*
              cp -rv /current-data/* /data
              tar zcvf neo4j-local-dev-`date "+%Y.%m.%d"`.tar.gz /data
              neo4j-admin dump --database=graph.db --to=/neo4j-backup/neo4j-local-dev-`date "+%Y.%m.%d"`.dump
            #command: ["sleep","10000000000"]
            env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: 'yes'
            volumeMounts:
            - name: neo4j-backup
              mountPath: /neo4j-backup
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-current-data
              mountPath: /current-data
          volumes:
          - name: neo4j-backup
            hostPath:
              path: /tsjr-data/databackup/neo4j-backup
              type: DirectoryOrCreate
          - name: neo4j-data
            hostPath:
              path: /k8s-pv-data/neo4j-zach
              type: Directory
          - name: neo4j-current-data
            hostPath:
              path: /k8s-pv-data/neo4j-neo4j-core-neo4j-core-1-pvc-52fcdb93-e0f5-11e9-badb-1626ccc266d7
              type: Directory
          restartPolicy: OnFailure
