---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: neo4j
  labels:
    app: neo4j-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neo4j-core
  serviceName: neo4j-core
  template:
    metadata:
      labels:
        app: neo4j-core
    spec:
      containers:
      - name: neo4j-core
        image: neo4j:3.5.5-enterprise
        imagePullPolicy: IfNotPresent
        env:
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
          - name: NEO4J_dbms_connectors_default__advertised__address
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NEO4J_dbms_mode
            value: "CORE"
          - name: NEO4J_AUTH
            value: "neo4j/zach"
          - name: NEO4J_causal__clustering_minimum__core__cluster__size__at__formation
            value: "2"
          - name: NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime
            value: "2"
          - name: NEO4J_causal__clustering_discovery__type  # 
            value: "LIST"
          - name: NEO4J_causal__clustering_initial__discovery__members  
            value: "neo4j-core-0.neo4j-core.neo4j.svc.cluster.zach:5000,neo4j-core-1.neo4j-core.neo4j.svc.cluster.zach:5000"
          - name: NEO4J_causal__clustering_discovery__advertised__address
            value: $(NEO4J_dbms_connectors_default__advertised__address):5000
          - name: NEO4J_causalClustering_transactionAdvertisedAddress
            value: $(NEO4J_dbms_connectors_default__advertised__address):6000
          - name: NEO4J_causalClustering_raftAdvertisedAddress
            value: $(NEO4J_dbms_connectors_default__advertised__address):7000
          - name: NEO4J_metrics_prometheus_enabled
            value: "true"
          - name: NEO4J_metrics_prometheus_endpoint
            value: 0.0.0.0:2004
        volumeMounts:
        - name: neo4j-core
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: neo4j-core
      annotations:
        volume.beta.kubernetes.io/storage-class: "zach-nfs-local-1"  
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 200Mi
