---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-core
  namespace: neo4j
spec:
  selector:
    app: neo4j-core
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 7474
      nodePort: 27474
      targetPort: 7474
    - protocol: TCP
      name: blot
      port: 7687
      nodePort: 27687
      targetPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: neorj-read-replica
  namespace: neo4j
spec:
  selector:
    app: neorj-read-replica
  ports:
  - protocol: TCP
    port: 7687
    targetPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-master
  namespace: neo4j
spec:
  selector:
    statefulset.kubernetes.io/pod-name: neo4j-core-0
  type: NodePort
  ports:
    - protocol: TCP
      name: blot
      port: 7687
      nodePort: 27688
      targetPort: 7687

