apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: mysql-zach
  template:
    metadata:
      labels:
        type: backend
        service: mysql-zach
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ZACHWANG

