modules:
  http_2xx_check: # http 监测模块
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200,302,401] # Defaults to 2xx
      method: GET
        # headers:
          # Host: vhost.example.com
          # Accept-Language: en-US
  http_post_2xx: # http post 监测模块
    prober: http
    http:
      method: POST
      headers:
        Content-Type: application/json
      body: '{}'
  tcp_connect: # tcp 监测模块
    prober: tcp
  ping: # icmp 检测模块
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  dns_examplecom_check:
    prober: dns
    dns:
      preferred_ip_protocol: "ip4"
      query_name: "www.zach.com"
  https_post_health:
    prober: http
    http:
      method: POST
      valid_http_versions: ["HTTP/1.1","HTTP/2"]
      fail_if_not_ssl: true
      headers:
        Content-Type: application/json
      body: '{"username": "dev", "password": "pwd"}'

  http_basic_auth_label:
    prober: http
    timeout: 10s
    http:
      method: POST
      basic_auth:
        username: "admin"
        password: "admin"
      valid_status_codes: [200]
      
  http_api_detection:
    prober: http
    timeout: 10s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1","HTTP/2"]
      valid_status_codes: [405,400]