apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: accept-all-ingress
  namespace: dev
spec:
  podSelector: {}
  # This rule which means ALL ingress flow will be accepted 
  ingress:
  - {}
  policyTypes:
  - Ingress
