apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    run: busybox
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
spec:
  containers:
  - name: busybox
    image: busybox:1.28.3
    imagePullPolicy: IfNotPresent
    command: ["sleep","3600"]
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: busybox-pass
          items:
          - key: ROOT_PASS
            path: my-group/my-password
      - downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
      - configMap:
          name: busybox-users
          items:
          - key: ROOT_USER
            path: my-group/my-username
